export const SoundMap: { [key: string]: any } = {
  Alpha: require('../assets/sounds/alpha.mp3'),
  Bravo: require('../assets/sounds/bravo.mp3'),
  Charlie: require('../assets/sounds/charlie.mp3'),
  Delta: require('../assets/sounds/delta.mp3'),
  Echo: require('../assets/sounds/echo.mp3'),
  Foxtrot: require('../assets/sounds/foxtrot.mp3'),
  Golf: require('../assets/sounds/golf.mp3'),
  Hotel: require('../assets/sounds/hotel.mp3'),
  India: require('../assets/sounds/india.mp3'),
  Juliet: require('../assets/sounds/juliet.mp3'),
  Kilo: require('../assets/sounds/kilo.mp3'),
  Lima: require('../assets/sounds/lima.mp3'),
  Mike: require('../assets/sounds/mike.mp3'),
  November: require('../assets/sounds/november.mp3'),
  Oscar: require('../assets/sounds/oscar.mp3'),
  Papa: require('../assets/sounds/papa.mp3'),
  Quebec: require('../assets/sounds/quebec.mp3'),
  Romeo: require('../assets/sounds/romeo.mp3'),
  Sierra: require('../assets/sounds/sierra.mp3'),
  Tango: require('../assets/sounds/tango.mp3'),
  Uniform: require('../assets/sounds/uniform.mp3'),
  Victor: require('../assets/sounds/victor.mp3'),
  Whiskey: require('../assets/sounds/whiskey.mp3'),
  'X-ray': require('../assets/sounds/x-ray.mp3'),
  Yankee: require('../assets/sounds/yankee.mp3'),
  Zulu: require('../assets/sounds/zulu.mp3'),
};
